### ISSUE TITLE
parse error on multiple function args

### ISSUE THREAD

**Issue by juliangruber** [tj/node-actorify#8]
``` js
actor.send('foo', function(){}, function(){});
```

causes the server to throw:

```
Uncaught SyntaxError: Unexpected token u
      at Object.parse (native)
      at unpack (***/node_modules/actorify/node_modules/amp-message/index.js:136:32)
      at decode (***/node_modules/actorify/node_modules/amp-message/index.js:83:15)
      at new Message (***/node_modules/actorify/node_modules/amp-message/index.js:35:37)
      at Actor.onmessage (***/node_modules/actorify/index.js:70:13)
      at Parser.EventEmitter.emit (events.js:101:17)
      at Parser._write (***/node_modules/actorify/node_modules/amp/lib/stream.js:91:16)
      at doWrite (_stream_writable.js:257:12)
      at writeOrBuffer (_stream_writable.js:244:5)
      at Parser.Writable.write (_stream_writable.js:191:11)
      at Socket.ondata (_stream_readable.js:534:20)
      at Socket.EventEmitter.emit (events.js:101:17)
      at readableAddChunk (_stream_readable.js:156:16)
      at Socket.Readable.push (_stream_readable.js:123:10)
      at TCP.onread (net.js:509:20)
```

**Comment by tsouza** [comment]
I believe that sending function arguments is not supported.

If this is intended you should call function.toString() on the client and eval on the server.

**Comment by juliangruber** [comment]
I'm more considered about a random malfunctioning client sending this and the server crashes without you being able to catch that error
